name: Test GitHub Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Secret
        env:
          MY_SECRET: ${{ secrets.SECRET_KEY }}
        run: echo "The secret is: $MY_SECRET"
